server:
  port: ${PORT:8080}


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banco_test
    username: root
    password: admin15
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        show-sql: true
        format_sql: true
        use_sql_comments: true
